
set_property PACKAGE_PIN E3 [get_ports clk_100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports button]
#set_property IOSTANDARD LVCMOS33 [get_ports Data_Mem_display_reg]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN J15 [get_ports rst]
#set_property PACKAGE_PIN N14 [get_ports Data_Mem_display_reg]
set_property PACKAGE_PIN M18 [get_ports button]
set_property PACKAGE_PIN U13 [get_ports {anode[7]}]
set_property PACKAGE_PIN K2 [get_ports {anode[6]}]
set_property PACKAGE_PIN T14 [get_ports {anode[5]}]
set_property PACKAGE_PIN P14 [get_ports {anode[4]}]
set_property PACKAGE_PIN J14 [get_ports {anode[3]}]
set_property PACKAGE_PIN T9 [get_ports {anode[2]}]
set_property PACKAGE_PIN J18 [get_ports {anode[1]}]
set_property PACKAGE_PIN J17 [get_ports {anode[0]}]
set_property PACKAGE_PIN H15 [get_ports {SSD[7]}]
set_property PACKAGE_PIN L18 [get_ports {SSD[6]}]
set_property PACKAGE_PIN T11 [get_ports {SSD[5]}]
set_property PACKAGE_PIN P15 [get_ports {SSD[4]}]
set_property PACKAGE_PIN K13 [get_ports {SSD[3]}]
set_property PACKAGE_PIN K16 [get_ports {SSD[2]}]
set_property PACKAGE_PIN R10 [get_ports {SSD[1]}]
set_property PACKAGE_PIN T10 [get_ports {SSD[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk_light_display]
set_property PACKAGE_PIN K15 [get_ports clk_light_display]

create_clock -period 5.000 -name clk_100mhz -waveform {0.000 2.500} [get_ports clk_100mhz]
