set_property PACKAGE_PIN E3 [get_ports i_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_Switch_1]
set_property IOSTANDARD LVCMOS33 [get_ports i_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN M18 [get_ports i_Switch_1]
set_property PACKAGE_PIN H17 [get_ports led]
