@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 08 17:38:57 +0500 2023
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim Pipelined_Top_Testbench_behav -key {Behavioral:Pipeline_Top_SimSet:Functional:Pipelined_Top_Testbench} -tclbatch Pipelined_Top_Testbench.tcl -view E:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/Pipline_5_stage_Processor_V_1.0/Pipline_5_stage_Processor_V_1.0.srcs/Pipeline_Top_SimSet/imports/Single_Cycle_Processor_V_1.2/Five_Stage_Pipline_Top_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
