# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.cache/wt [current_project]
set_property parent.project_path D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/ALU.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/ALU_Decoder.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Adder.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Main_Decoder.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Control_Unit_Top.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Data_Memory.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Decode_Cycle.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Mux_2_by_1.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Mux_3_by_1.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Execute_Cycle.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Program_Counter.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Instruction_Memory.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/PC_Adder.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Fetch_Cycle.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Hazard_Unit.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/new/MAC_Decoder.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Matric_MAC.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Memory_Cycle.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Multplex_Reg_Disp.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Register_File.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Sign_Extend.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/WriteBack_Cycle.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/debouncer_clock.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Slow_Clock.v
  D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/sources_1/imports/new/Five_Stage_Pipeline_Top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files D:/UNI/FYP/FYP--Risc-V-32-bit-Matrix-Mac/Project/RISC_V_MAC_Processor_V2.0/RISC_V_MAC_Processor.srcs/constrs_1/new/const.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Pipeline_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Pipeline_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Pipeline_top_utilization_synth.rpt -pb Pipeline_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
