######################################################################
##
## Filename: ALU.do
## Created on: Mon Jun 26 16:31:40 2023
##
##  Auto generated by Vivado for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the simulation directory and will not be removed on
##  subsequent simulation flow runs from Vivado.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#

#
# Create work library
#
vlib work
vlib msim/xil_defaultlib

#
# Map libraries
#
vmap xil_defaultlib msim/xil_defaultlib

#
# Design sources
#
vlog  -incr  -work xil_defaultlib  "E:/UNI/FYP/practice/practice_1/practice_1.srcs/sources_1/new/ALU.v"

#
# Add global set/reset
#
vlog -work xil_defaultlib "C:/Xilinx/Vivado/2014.2/data/verilog/src/glbl.v"

#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.ALU xil_defaultlib.glbl

#
# Source wave do file
#
do {ALU_wave.do}

#
# Set the window types
#
view wave
view structure
view signals

#
# Source user do file (UDO)
#
do {ALU.udo}

#
# Run simulation for this time
#
run 1000ns


#
# End
#
