######################################################################
##
## Filename: ALU_wave.do
## Created on: Mon Jun 26 16:31:40 2023
##
##  Auto generated by Vivado for Behavioral Simulation
##
##  You may want to edit this file to control the simulation
##
######################################################################
add wave *
add wave /glbl/GSR
